
package com.googlecode.bdoc.test.log.config;

/**
 * Example generated by BddDoc4J
 */
public enum Story {

	STACK(1, "As a developer", "I want to push objects to a stack", "so that objects can be poped last in first out");

	private Integer id;
	private String[] narrative;

	Story(Integer id, String ... narrative ) {
		this.id = id;
		this.narrative = narrative;
	}

	public Integer id() {
		return id;
	}

	public String[] narrative() {
		return narrative;
	}
}
